pull_request_rules:
  - name: automatic merge on CI success and labeled
    conditions:
      - status-success="ci/circleci: haskell-build-and-test"
      - label=merge this
    actions:
      merge:
        method: merge
      label:
        remove:
          - merge this
