version: 2.1

workflows:
  version: 2
  test-and-gh-page:
    jobs:
      - haskell-install
      - haskell-build-and-test:
          requires:
            - haskell-install
      - haddock-build:
          requires:
            - haskell-install
          filters:
            branches:
              only: master
      - doxygen-build:
          filters:
            branches:
              only: master
      - gh-page-deploy:
          requires:
            - haskell-build-and-test
            - haddock-build
            - doxygen-build
          filters:
            branches:
              only: master

jobs:
  haskell-install:
    executor: stack-minimal
    steps:
      - checkout
      - restore-all-haskell-caches
      - stack-setup
      - stack-build-deps
      - save-all-haskell-caches

  haskell-build-and-test:
    executor: stack-minimal
    steps:
      - checkout
      - restore-all-haskell-caches

      - stack-verify-all

  haddock-build:
    executor: stack-minimal
    steps:
      - checkout
      - restore-all-haskell-caches

      - stack-haddock
      - run: "mv $(stack path --local-doc-root) /tmp/haddock"
      - persist_to_workspace:
          root: "/tmp"
          paths:
            - "./haddock/*"

  doxygen-build:
    executor: doxygen-minimal
    steps:
      - checkout

      - doxygen
      - run: "mv runtime/doc/html /tmp/doxygen"
      - persist_to_workspace:
          root: "/tmp"
          paths:
            - "./doxygen/*"

  gh-page-deploy:
    executor: node-minimal
    steps:
      - checkout
      - restore-all-node-caches
      - attach_workspace:
          # Use relative path because of gh-pages cli
          at: ".gh-pages/"
      - copy-templates

      - deploy-documents
      - save-all-node-caches

executors:
  stack-minimal:
    docker:
      - image: cutelang/stack-small:lts-13.27
  doxygen-minimal:
    docker:
      - image: cutelang/doxygen-small:1.8.15
  node-minimal:
    docker:
      - image: circleci/node:12

commands:
  stack-setup:
    description: "Setup haskell tool stack."
    steps:
      - run: stack setup -j2
  stack-build-deps:
    description: "Build only dependencies with haskell tool stack."
    steps:
      - run: stack build --only-dependencies -j2
      - run: stack test --only-dependencies -j2
      - run: stack haddock --only-dependencies -j2
  stack-test-all:
    description: "Test everything related with the haskell codes in this repo with haskell tool stack."
    steps:
      - run: stack test -j2
  stack-build-all:
    description: "Build everything related with the haskell codes in this repo with haskell tool stack."
    steps:
      - run: stack build -j2
  stack-verify-all:
    description: "Verify everything related with the haskell codes in this repo with haskell tool stack."
    steps:
      - stack-test-all
      - stack-build-all

  stack-haddock:
    description: "Build haddock documents for the haskell codes in this repo."
    steps:
      - run: stack haddock -j2

  doxygen:
    description: "Build doxygen documents for runtime."
    steps:
      - run: |
          cd runtime
          make html
          cd ..

  copy-templates:
    description: "Copy template files to the document directory."
    steps:
      # Use relative path because of gh-pages cli
      - run: cp -r .gh-page-templates/* .gh-pages/

  deploy-documents:
    description: "Deploy documents."
    steps:
      - add_ssh_keys:
          fingerprints:
            - "f4:d3:a7:2e:7a:2e:8f:a2:b6:72:35:cb:7f:82:9f:fd"
      - deploy:
          # gh-pages cli does not support absolute paths.
          # It recognizes an absolute path as a relative path from the project root.
          command: |
            git config user.email "miniCUTE-documents@github.com"
            git config user.name "miniCUTE-documents"
            npx gh-pages --dotfiles --message "Update to sync with ${CIRCLE_SHA1} [skip ci]" -d .gh-pages/

  restore-all-haskell-caches:
    description: "Restore all cached parts of haskell packages."
    steps:
      - restore_cache:
          name: Restore Global Data
          keys:
            - circleci-minicute-haskell-global-v3.1-{{ arch }}-{{ checksum "stack.yaml" }}-{{ checksum "common-syntax/package.yaml" }}-{{ checksum "executables/package.yaml" }}-{{ checksum "extensions/package.yaml" }}-{{ checksum "g-machine-syntax/package.yaml" }}-{{ checksum "g-machinizer/package.yaml" }}-{{ checksum "llvm-generator/package.yaml" }}-{{ checksum "minicute-syntax/package.yaml" }}
            - circleci-minicute-haskell-global-v3.1-{{ arch }}-{{ checksum "stack.yaml" }}
            - circleci-minicute-haskell-global-v3.1-{{ arch }}

      - restore_cache:
          name: Restore Project Local Data
          keys:
            - circleci-minicute-project-local-v3.1-{{ arch }}-{{ checksum "stack.yaml" }}-{{ checksum "common-syntax/package.yaml" }}-{{ checksum "executables/package.yaml" }}-{{ checksum "extensions/package.yaml" }}-{{ checksum "g-machine-syntax/package.yaml" }}-{{ checksum "g-machinizer/package.yaml" }}-{{ checksum "llvm-generator/package.yaml" }}-{{ checksum "minicute-syntax/package.yaml" }}

      - restore_cache:
          name: Restore Common syntax Local Data
          keys:
            - circleci-minicute-common-syntax-local-v3.1-{{ arch }}-{{ checksum "stack.yaml" }}-{{ checksum "common-syntax/package.yaml" }}
      - restore_cache:
          name: Restore Executables Local Data
          keys:
            - circleci-minicute-executables-local-v3.1-{{ arch }}-{{ checksum "stack.yaml" }}-{{ checksum "executables/package.yaml" }}
      - restore_cache:
          name: Restore Extensions Local Data
          keys:
            - circleci-minicute-extensions-local-v3.1-{{ arch }}-{{ checksum "stack.yaml" }}-{{ checksum "extensions/package.yaml" }}
      - restore_cache:
          name: Restore G-machine syntax Local Data
          keys:
            - circleci-minicute-g-machine-syntax-local-v3.1-{{ arch }}-{{ checksum "stack.yaml" }}-{{ checksum "g-machine-syntax/package.yaml" }}
      - restore_cache:
          name: Restore G-Machinizer Local Data
          keys:
            - circleci-minicute-g-machinizer-local-v3.1-{{ arch }}-{{ checksum "stack.yaml" }}-{{ checksum "g-machinizer/package.yaml" }}
      - restore_cache:
          name: Restore LLVM-generator Local Data
          keys:
            - circleci-minicute-llvm-generator-local-v3.1-{{ arch }}-{{ checksum "stack.yaml" }}-{{ checksum "llvm-generator/package.yaml" }}
      - restore_cache:
          name: Restore miniCUTE syntax Local Data
          keys:
            - circleci-minicute-minicute-syntax-local-v3.1-{{ arch }}-{{ checksum "stack.yaml" }}-{{ checksum "minicute-syntax/package.yaml" }}

  save-all-haskell-caches:
    description: "Save all cachable parts of haskell packages."
    steps:
      - save_cache:
          name: Cache Global Data
          key: circleci-minicute-haskell-global-v3.1-{{ arch }}-{{ checksum "stack.yaml" }}-{{ checksum "common-syntax/package.yaml" }}-{{ checksum "executables/package.yaml" }}-{{ checksum "extensions/package.yaml" }}-{{ checksum "g-machine-syntax/package.yaml" }}-{{ checksum "g-machinizer/package.yaml" }}-{{ checksum "llvm-generator/package.yaml" }}-{{ checksum "minicute-syntax/package.yaml" }}
          paths:
            - "~/.stack"

      - save_cache:
          name: Cache Project Local Data
          key: circleci-minicute-project-local-v3.1-{{ arch }}-{{ checksum "stack.yaml" }}-{{ checksum "common-syntax/package.yaml" }}-{{ checksum "executables/package.yaml" }}-{{ checksum "extensions/package.yaml" }}-{{ checksum "g-machine-syntax/package.yaml" }}-{{ checksum "g-machinizer/package.yaml" }}-{{ checksum "llvm-generator/package.yaml" }}-{{ checksum "minicute-syntax/package.yaml" }}
          paths:
            - ".stack-work"

      - save_cache:
          name: Cache Common syntax Local Data
          key: circleci-minicute-common-syntax-local-v3.1-{{ arch }}-{{ checksum "stack.yaml" }}-{{ checksum "common-syntax/package.yaml" }}
          paths:
            - "common-syntax/.stack-work"
      - save_cache:
          name: Cache Executables Local Data
          key: circleci-minicute-executables-local-v3.1-{{ arch }}-{{ checksum "stack.yaml" }}-{{ checksum "executables/package.yaml" }}
          paths:
            - "executables/.stack-work"
      - save_cache:
          name: Cache Extensions Local Data
          key: circleci-minicute-extensions-local-v3.1-{{ arch }}-{{ checksum "stack.yaml" }}-{{ checksum "extensions/package.yaml" }}
          paths:
            - "extensions/.stack-work"
      - save_cache:
          name: Cache G-Machine syntax Local Data
          key: circleci-minicute-g-machine-syntax-local-v3.1-{{ arch }}-{{ checksum "stack.yaml" }}-{{ checksum "g-machine-syntax/package.yaml" }}
          paths:
            - "g-machine-syntax/.stack-work"
      - save_cache:
          name: Cache G-Machinizer Local Data
          key: circleci-minicute-g-machinizer-local-v3.1-{{ arch }}-{{ checksum "stack.yaml" }}-{{ checksum "g-machinizer/package.yaml" }}
          paths:
            - "g-machinizer/.stack-work"
      - save_cache:
          name: Cache LLVM-generator Local Data
          key: circleci-minicute-llvm-generator-local-v3.1-{{ arch }}-{{ checksum "stack.yaml" }}-{{ checksum "llvm-generator/package.yaml" }}
          paths:
            - "llvm-generator/.stack-work"
      - save_cache:
          name: Cache miniCUTE syntax Local Data
          key: circleci-minicute-minicute-syntax-local-v3.1-{{ arch }}-{{ checksum "stack.yaml" }}-{{ checksum "minicute-syntax/package.yaml" }}
          paths:
            - "minicute-syntax/.stack-work"

  restore-all-node-caches:
    description: "Restore all cached parts of node packages."
    steps:
      - restore_cache:
          name: Restore Global Data
          keys:
            - circleci-minicute-node-global-v3.1
            - circleci-minicute-node-global-v3.1
            - circleci-minicute-node-global-v3

  save-all-node-caches:
    description: "Save all cachable parts of node packages."
    steps:
      - save_cache:
          name: Cache Global Data
          key: circleci-minicute-node-global-v3.1
          paths:
            - "~/.npm"
